apiVersion: apps/v1
kind: Deployment

metadata:
  name: docker-sage-deployment
  namespace: dev

spec:
  replicas: 3

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: docker-sage

  template:
    metadata:
      labels:
        app: docker-sage

    spec:
      serviceAccountName: app-sa

      containers:
        - name: app
          image: docker-sage-assignment:v5
          imagePullPolicy: Never

          ports:
            - containerPort: 8080

          env:
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ENV

            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: LOG_LEVEL

            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: password

          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"

            limits:
              cpu: "500m"
              memory: "256Mi"
              