apiVersion: v1
kind: Service

metadata:
  name: docker-sage-service
  namespace: dev

spec:
  type: ClusterIP

  selector:
    app: docker-sage

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      